name: Build and Upload .NET Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install .NET Framework 3.5
      run: |
        dism /online /enable-feature /featurename:NetFx3 /All /LimitAccess
      shell: powershell # Use PowerShell for the command

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mother3SpriteEditor
        path: ./bin
