name: Build and Upload .NET Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore MOTHER3SpriteEditor.sln

      - name: Build with MSBuild
        shell: pwsh
        run: |
          $msbuild = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          & "$msbuild" MOTHER3SpriteEditor.sln /p:Configuration=Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mother3SpriteEditor
          path: 'MOTHER3SpriteEditor/bin/Release/**'
